### PR TITLE
 (fix)[assembly]: make the u32assert error clearer

### LINKED ISSUE #213: Update u32assert assembly instruction
`u32assert` instruction checks whether the top value of the stack is u32 or not. It is currently using 3 VM cycle using these three VM instructions: `U32SPLIT EQZ ASSERT`. We would like to update the assembly instruction with `PAD U32ASSERT2 DROP` as it gives a better error message as echoed by Bobbin in this [PR](https://github.com/maticnetwork/miden/pull/202). The test cases also needs to updated accordingly as some u32 operations might fail due to the assembly instruction udpate.

### PR DESCRIPTION
**Pull request by DeimosTheMisthios**
Change the `u32assert` assembly instruction from `U32SPLIT EQZ ASSERT`
to `PAD U32ASSERT2 DROP` to give the better error message `NotU32Value`
instead of `FailedAssertion`. Update associated tests.

Closes #213

### CODE REVIEW

File: miden/tests/integration/operations/u32_ops/arithmetic_ops.rs [hunk 1]
```diff
@@ -34,16 +34,19 @@ fn u32add_fail() {
...
-    test.expect_error(TestError::ExecutionError("FailedAssertion"));
+    test.expect_error(TestError::ExecutionError("NotU32Value"));
 
     // should fail if a + b >= 2^32
     let a = u32::MAX;
     let b = 1_u64;
     let test = build_op_test!(asm_op, &[a as u64, b]);
+    // TODO: Discuss if the error thrown in handle_arithmetic_operation
+    // should be changed to NotU32Value somehow instead of FailedAssertion
+    // which is thrown when the result >= 2^32
```
Comment (bobbinth) [inline miden/tests/integration/operations/u32_ops/arithmetic_ops.rs:49]: Great point! Unfortunately, I don't see an easy way to do this without either significant impacting performance or refactoring the way we execute operations. For now, I'd remove this comment and create a separate issue for this.

**Review by bobbinth — CHANGES_REQUESTED** [review]
Looks great! Thank you for tackling this! I left one minor comment inline.

One other thing: it would be great to update how `u32assertw` works as well. I know it wasn't a part of the original issue, but it should be a fairly straightforward change. Specifically, instead of the current sequence which requires 18 cycles, we could do something like this (which requires just 6 cycles):
```
u32assert2
movup.3
movup.3
u32assert2
movup.3
movup.3
```

File: miden/tests/integration/operations/u32_ops/arithmetic_ops.rs (hunk 1 above)
Comment (DeimosTheMisthios) [reply miden/tests/integration/operations/u32_ops/arithmetic_ops.rs]: Created #218 for tracking this, thanks

File: assembly/src/parsers/u32_ops.rs [hunk 2]
```diff
@@ -88,29 +88,23 @@ pub fn parse_u32assert(span_ops: &mut Vec<Operation>, op: &Token) -> Result<(),
 
 /// Translates u32assert assembly instruction to VM operations.
 ///
-/// Implemented by executing `U32SPLIT EQZ ASSERT` on each element in the word.
+/// Implemented by executing `PAD U32ASSERT2 DROP` on each element in the word.
```
Comment (bobbinth) [inline assembly/src/parsers/u32_ops.rs:91]: very minor nit: `PAD U32ASSERT2 DROP` is not executed on each element in the word - but on each pair of elements in the word.

**Comment by bobbinth** [comment]
@DeimosTheMisthios - could you squash the commits to maybe 1 or 2? And I'll merge after that.

**Comment by DeimosTheMisthios** [comment]
Thanks @bobbinth, this has been actioned.

**Comment by bobbinth** [comment]
@DeimosTheMisthios - awesome! Thank you!
